// Banco de dados de contas a receber
// Em produção, substituir por chamadas à API REST /financeiro/receber

export const contasReceber = [
  {
    id: 1,
    cliente_nome: 'Carlos Alves',
    initials: 'CA',
    referente: 'Câmeras — Parcela 2/3',
    valor: 316.67,
    vencimento: '10/06/2025',
    tipo: 'Parcelado',
    status: 'vencido',
    dias_atraso: 8,
  },
  {
    id: 2,
    cliente_nome: 'Maria Santos',
    initials: 'MS',
    referente: 'Serviço avulso',
    valor: 900.00,
    vencimento: '12/06/2025',
    tipo: 'À vista',
    status: 'vencido',
    dias_atraso: 6,
  },
  {
    id: 3,
    cliente_nome: 'Ana Lima',
    initials: 'AL',
    referente: 'Site — Parcela 1/6',
    valor: 466.67,
    vencimento: '20/06/2025',
    tipo: 'Parcelado',
    status: 'pendente',
    dias_atraso: 0,
  },
  {
    id: 4,
    cliente_nome: 'Pedro Ferreira',
    initials: 'PF',
    referente: 'Suporte TI',
    valor: 350.00,
    vencimento: '30/06/2025',
    tipo: 'À vista',
    status: 'pendente',
    dias_atraso: 0,
  },
  {
    id: 5,
    cliente_nome: 'Fernanda T.',
    initials: 'FT',
    referente: 'Fechadura eletrônica',
    valor: 320.00,
    vencimento: '05/06/2025',
    tipo: 'À vista',
    status: 'pago',
    dias_atraso: 0,
  },
]
