// Banco de dados de vendas e orçamentos
// Em produção, substituir por chamadas à API REST /vendas

export const vendas = [
  {
    id: 1,
    cliente_nome: 'Carlos Alves',
    initials: 'CA',
    servico: 'Instalação câmeras',
    valor: 950.00,
    material: 380.00,
    pagamento: '3× R$ 316,67',
    prazo: '20/06',
    status: 'vencido',
    kanban_status: 'recebido',
  },
  {
    id: 2,
    cliente_nome: 'Ana Lima',
    initials: 'AL',
    servico: 'Site institucional',
    valor: 2800.00,
    material: null,
    pagamento: '6× R$ 466,67',
    prazo: '30/07',
    status: 'aprovado',
    kanban_status: 'aprovado',
  },
  {
    id: 3,
    cliente_nome: 'Maria Santos',
    initials: 'MS',
    servico: 'Manutenção de rede',
    valor: 600.00,
    material: 120.00,
    pagamento: 'À vista',
    prazo: '14/06',
    status: 'recebido',
    kanban_status: 'concluido',
  },
  {
    id: 4,
    cliente_nome: 'Pedro Ferreira',
    initials: 'PF',
    servico: 'Suporte TI',
    valor: 350.00,
    material: null,
    pagamento: 'À vista',
    prazo: '18/06',
    status: 'andamento',
    kanban_status: 'andamento',
  },
  {
    id: 5,
    cliente_nome: 'Pedro Rocha',
    initials: 'PR',
    servico: 'Reforma elétrica',
    valor: 1200.00,
    material: null,
    pagamento: 'À vista',
    prazo: '15/07',
    status: 'orcamento',
    kanban_status: 'orcamento',
    data_envio: '28/05',
  },
  {
    id: 6,
    cliente_nome: 'Empresa XYZ',
    initials: 'EX',
    servico: 'Câmeras CFTV',
    valor: 3500.00,
    material: null,
    pagamento: 'À vista',
    prazo: '20/07',
    status: 'orcamento',
    kanban_status: 'orcamento',
    data_envio: '01/06',
  },
  {
    id: 7,
    cliente_nome: 'Loja Bela',
    initials: 'LB',
    servico: 'Wi-Fi corporativo',
    valor: 800.00,
    material: null,
    pagamento: 'À vista',
    prazo: '25/07',
    status: 'orcamento',
    kanban_status: 'orcamento',
    data_envio: '03/06',
  },
  {
    id: 8,
    cliente_nome: 'Marcos Oliveira',
    initials: 'MO',
    servico: 'Suporte TI mensal',
    valor: 450.00,
    material: null,
    pagamento: 'À vista',
    prazo: '28/06',
    status: 'aprovado',
    kanban_status: 'aprovado',
    data_envio: '12/06',
  },
  {
    id: 9,
    cliente_nome: 'Restaurante Sabor',
    initials: 'RS',
    servico: 'Infra de rede',
    valor: 1800.00,
    material: null,
    pagamento: 'À vista',
    prazo: '30/06',
    status: 'andamento',
    kanban_status: 'andamento',
    data_envio: '08/06',
  },
  {
    id: 10,
    cliente_nome: 'Clínica Vida',
    initials: 'CV',
    servico: 'CFTV + alarme',
    valor: 2200.00,
    material: null,
    pagamento: 'À vista',
    prazo: '05/07',
    status: 'andamento',
    kanban_status: 'andamento',
    data_envio: '09/06',
  },
  {
    id: 11,
    cliente_nome: 'Roberto Costa',
    initials: 'RC',
    servico: 'SEO Google',
    valor: 700.00,
    material: null,
    pagamento: 'À vista',
    prazo: '30/06',
    status: 'andamento',
    kanban_status: 'andamento',
    data_envio: '11/06',
  },
  {
    id: 12,
    cliente_nome: 'João Mendes',
    initials: 'JM',
    servico: 'Notebook — SSD',
    valor: 480.00,
    material: null,
    pagamento: 'À vista',
    prazo: '15/06',
    status: 'concluido',
    kanban_status: 'concluido',
    data_envio: '15/06',
  },
  {
    id: 13,
    cliente_nome: 'Fernanda Silva',
    initials: 'FS',
    servico: 'Fechadura eletrônica',
    valor: 320.00,
    material: null,
    pagamento: 'À vista',
    prazo: '10/06',
    status: 'recebido',
    kanban_status: 'recebido',
    data_envio: '10/06',
  },
  {
    id: 14,
    cliente_nome: 'Tech Office',
    initials: 'TO',
    servico: 'Suporte TI',
    valor: 950.00,
    material: null,
    pagamento: 'À vista',
    prazo: '11/06',
    status: 'recebido',
    kanban_status: 'recebido',
    data_envio: '11/06',
  },
]

export const statusLabels = {
  orcamento: 'Orçamento',
  aprovado: 'Aprovado',
  andamento: 'Em andamento',
  concluido: 'Concluído',
  recebido: 'Recebido',
  vencido: 'Vencido',
}

export const kanbanColunas = ['orcamento', 'aprovado', 'andamento', 'concluido', 'recebido']

// Transições permitidas: cada status só pode ir para os próximos
export const transicoesPermitidas = {
  orcamento: ['aprovado', 'andamento'],
  aprovado:  ['andamento', 'concluido'],
  andamento: ['concluido', 'aprovado'],
  concluido: ['recebido', 'andamento'],
  recebido:  [], // status final — não pode voltar
}
